// @ts-nocheck
import {createClient} from "npm:@supabase/supabase-js@2.95.0"

const API='https://api.openai.com/v1'
const MODEL=()=>Deno.env.get('OPENAI_REFINERY_ADJUDICATOR_MODEL')||'gpt-4.1-mini'

function admin(){const u=Deno.env.get('SUPABASE_URL')||'';let k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!k)try{k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||''}catch{};if(!u||!k)throw Error('ENV');return createClient(u,k,{auth:{persistSession:false}})}
function key(){const k=Deno.env.get('OPENAI_API_KEY')||'';if(!k)throw Error('NO_OPENAI_API_KEY');return k}
async function oa(body){const r=await fetch(`${API}/responses`,{method:'POST',headers:{Authorization:`Bearer ${key()}`,'Content-Type':'application/json'},body:JSON.stringify(body)});let p={};try{p=await r.json()}catch{};if(!r.ok)throw Error(`OPENAI_${r.status}:${p?.error?.message||JSON.stringify(p)}`);return p}
function outputText(p){if(typeof p?.output_text==='string')return p.output_text;for(const i of p?.output||[])for(const c of i?.content||[])if(c?.type==='output_text'&&typeof c.text==='string')return c.text;return null}
const POLICY=`You are the release adjudicator for the VanHub UK customer-job intake engine. Candidate knowledge came from real-call refinery, trade-scenario refinery, historic jobs, FAQs and old operating material. Candidates are NOT automatically true current policy. Reconcile them into current canonical engineering rules.

HARD CURRENT INVARIANTS — these outrank candidate frequency or historic wording:
1. Customer operational state is evidence-grounded. LLM/retrieval facts are candidates only. A canonical field changes only from acceptable customer evidence in the conversation. Retrieved refinery/trade knowledge is policy/questioning context only and is NEVER customer evidence.
2. Town/area is sufficient route detail to continue; postcode is useful and improves quote accuracy but is not mandatory when town/area is known.
3. Bounded flexible dates such as 'any day next week' are valid date information. Do not require an exact date when the customer genuinely supplies a useful bounded window. Clear relative/weekday dates should be canonically resolved without inventing a different date.
4. Vague loads are not quote-grade: 'multiple items', 'van full', 'not much', 'some furniture', 'a few boxes', 'boxes' without useful quantity/context, or bedroom count alone do not establish load volume. A house/flat bedroom count alone is insufficient. Approximate counts are acceptable when the item noun/context is established.
5. Customer understatement must be guarded against: long carries, internal/external stairs, parking, dismantling, loose/unboxed contents and fit/access can materially change a quote.
6. Helper presence is not lifting capability. 'Loads of us helping' or people being present is insufficient. Only explicit capable/willing lift/load/unload/carry evidence counts. Partial help for boxes does not count as help for a bulky sofa.
7. Dismantling responsibility must be explicit. 'It comes apart into sections' proves separability only; it does NOT prove the customer will dismantle it. Customer/driver/already-dismantled responsibility requires literal compatible evidence.
8. Washing-machine/dishwasher plumbing is not a normal driver obligation. Drivers may refuse; intake should identify disconnection/reconnection expectations rather than promise plumbing.
9. House moves containing a motorbike remain house_move. A non-running/non-rolling motorbike needs an explicit viable loading plan.
10. Unusual late starts such as 9pm must be confirmed before progressing past that ambiguity.
11. Multi-stop routes must preserve every explicit collection/delivery in structured state even when one location is the primary canonical endpoint.
12. Historic business policy (pricing, deposits, driver sourcing, waste arrangements, etc.) is not current policy unless separately confirmed by current canonical product policy.
13. Safety-sensitive explicit evidence can trigger manual suitability review; do not invent hazards absent from customer evidence.
14. Current release target is the chatbot intake engine only. Handoff/FAQ knowledge may be advisory, but must not widen intake scope or create jobs during QA.

For each candidate, decide whether it should become a canonical release rule, remain runtime/advisory knowledge, be marked historic-only, or be rejected as overstatement/unsafe inference. Prefer narrow rules that drivers can actually quote from. Generate only synthetic test conversations; do not reproduce personal or identifiable source details.`
const SCHEMA={type:'object',additionalProperties:false,required:['domain','decision_summary','canonical_rules','advisory_rules','historic_only','rejected_claims'],properties:{domain:{type:'string'},decision_summary:{type:'string'},canonical_rules:{type:'array',items:{type:'object',additionalProperties:false,required:['importance','rule','bot_should','bot_must_not','deterministic_guard','evidence_requirement','source_files','conflict_notes','tests'],properties:{importance:{type:'string',enum:['critical','high','medium']},rule:{type:'string'},bot_should:{type:'string'},bot_must_not:{type:['string','null']},deterministic_guard:{type:'boolean'},evidence_requirement:{type:'string'},source_files:{type:'array',items:{type:'string'}},conflict_notes:{type:['string','null']},tests:{type:'array',items:{type:'object',additionalProperties:false,required:['turns','expected_behavior'],properties:{turns:{type:'array',items:{type:'string'}},expected_behavior:{type:'string'}}}}}}},advisory_rules:{type:'array',items:{type:'object',additionalProperties:false,required:['rule','reason','source_files'],properties:{rule:{type:'string'},reason:{type:'string'},source_files:{type:'array',items:{type:'string'}}}}},historic_only:{type:'array',items:{type:'object',additionalProperties:false,required:['claim','reason','source_files'],properties:{claim:{type:'string'},reason:{type:'string'},source_files:{type:'array',items:{type:'string'}}}}},rejected_claims:{type:'array',items:{type:'object',additionalProperties:false,required:['claim','reason','source_files'],properties:{claim:{type:'string'},reason:{type:'string'},source_files:{type:'array',items:{type:'string'}}}}}}}
function policyFlags(domain,x){const s=JSON.stringify(x?.canonical_rules||[]).toLowerCase(),f=[];if(/postcode.{0,30}(mandatory|required|must have)|(?:mandatory|required).{0,30}postcode/.test(s))f.push('POSTCODE_MANDATORY_CONFLICT');if(/exact date.{0,30}(mandatory|required|must)|(?:mandatory|required).{0,30}exact date/.test(s))f.push('EXACT_DATE_MANDATORY_CONFLICT');if(/(?:plenty|loads) of (?:help|helpers).{0,60}(satisf|counts as|is enough)/.test(s))f.push('VAGUE_HELP_ACCEPTED');if(/comes apart.{0,80}customer (?:will|must) dismantle/.test(s))f.push('DISMANTLING_RESPONSIBILITY_INFERRED');if(/retriev.{0,80}(?:customer evidence|populate.*field)/.test(s)&&!/never customer evidence/.test(s))f.push('RETRIEVAL_EVIDENCE_CONFLICT');return f}
async function candidates(sb,domain){const [pr,mr]=await Promise.all([sb.from('qa_refinery_distill_parts').select('file_id,part_index,distilled').eq('status','distilled'),sb.from('qa_refinery_distill').select('file_id,filename,source_type')]);if(pr.error)throw pr.error;if(mr.error)throw mr.error;const meta=new Map((mr.data||[]).map(x=>[x.file_id,x])),out=[];for(const p of pr.data||[]){for(const u of p.distilled?.units||[]){if(u?.domain!==domain)continue;const m=meta.get(p.file_id)||{};out.push({source_file:m.filename||p.file_id,source_type:m.source_type||null,part_index:p.part_index,kind:u.kind,importance:u.importance,rule:u.rule,bot_should:u.bot_should,bot_must_not:u.bot_must_not,customer_pattern:u.customer_pattern,expected_test_behavior:u.expected_test_behavior,requires_deterministic_guard:u.requires_deterministic_guard,runtime_retrieval_only:u.runtime_retrieval_only})}}return out}
async function adjudicate(sb,domain){const cs=await candidates(sb,domain);if(!cs.length)throw Error('NO_CANDIDATES');await sb.from('qa_refinery_adjudication').upsert({domain,candidate_count:cs.length,status:'adjudicating',error:null,updated_at:new Date().toISOString()},{onConflict:'domain'});try{const body={model:MODEL(),store:false,max_output_tokens:14000,input:[{role:'system',content:POLICY},{role:'user',content:JSON.stringify({domain,candidate_count:cs.length,candidates:cs})}],text:{format:{type:'json_schema',name:'vanhub_refinery_adjudication',strict:true,schema:SCHEMA}}};const p=await oa(body),t=outputText(p);if(!t)throw Error('OPENAI_EMPTY');const canonical=JSON.parse(t),flags=policyFlags(domain,canonical);canonical.policy_flags=flags;if(flags.length)throw Error(`POLICY_FLAGS:${flags.join(',')}`);const u=await sb.from('qa_refinery_adjudication').update({status:'adjudicated',canonical,model:p.model||MODEL(),usage:p.usage||null,error:null,updated_at:new Date().toISOString()}).eq('domain',domain);if(u.error)throw u.error;return {domain,candidate_count:cs.length,canonical_rules:canonical.canonical_rules?.length||0,advisory_rules:canonical.advisory_rules?.length||0,historic_only:canonical.historic_only?.length||0,rejected_claims:canonical.rejected_claims?.length||0,status:'adjudicated'}}catch(e){const msg=e instanceof Error?e.message:String(e);await sb.from('qa_refinery_adjudication').update({status:'failed',error:msg,updated_at:new Date().toISOString()}).eq('domain',domain);throw e}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok');if(req.method!=='POST')return Response.json({error:'Method not allowed'},{status:405});let b={};try{b=await req.json()}catch{return Response.json({error:'Invalid JSON'},{status:400})};if(b.action!=='adjudicate_domain'||!String(b.domain||'').trim())return Response.json({error:'action=adjudicate_domain and domain required'},{status:400});try{return Response.json(await adjudicate(admin(),String(b.domain)))}catch(e){return Response.json({error:e instanceof Error?e.message:String(e)},{status:500})}})
