// @ts-nocheck
import {canon,generic,yes,no,unk,strip,today,add,vagueVolume} from './core.ts'
const WD={sunday:0,monday:1,tuesday:2,wednesday:3,thursday:4,friday:5,saturday:6}
export function nextWeekday(name){let base=today(),d=new Date(`${base}T12:00:00Z`),target=WD[String(name).toLowerCase()],delta=(target-d.getUTCDay()+7)%7;if(delta===0)delta=7;return add(base,delta)}
export function durationEstimate(m){let s=String(m||'').toLowerCase();let x=s.match(/\b(?:should|will|would|probably|likely|only|just|about|around|roughly|maybe|expect(?:ed)?(?: to)?)?\s*(?:take|last|be)\s+(?:about\s+|around\s+|roughly\s+|only\s+|just\s+)?((?:\d+(?:\.\d+)?|an?|one|two|three|four|five|six|seven|eight|nine|ten|half)\s*(?:minutes?|mins?|hours?|hrs?))\b/i);if(x)return x[1];x=s.match(/\b(?:job|move|journey|trip)\s+(?:should\s+)?(?:only\s+)?(?:take|be)\s+([^,.!?;]+?(?:minutes?|mins?|hours?|hrs?))\b/i);return x?.[1]||null}
export function distanceEstimate(m){let x=String(m||'').match(/\b(?:only|just|about|around|roughly|maybe)?\s*(\d+(?:\.\d+)?)\s*(miles?|mi|km|kilometres?|kilometers?)\b/i);return x?.[0]||null}
export function relativeReference(m){let x=String(m||'').match(/\b(down the road(?: from me)?|up the road(?: from me)?|round the corner(?: from me)?|around the corner(?: from me)?|nearby|near me|close by|not far|local job|just over there)\b/i);return x?.[1]||null}
export function vanLoadClaim(m){let s=canon(m);let x=s.match(/\b((?:a |one |1 )?(?:(?:3\.?5\s*t(?:onne)?|lwb|mwb|swb|small|medium|large|luton|transit)\s+)?van(?: ?load)?(?: full)?|(?:full|half) (?:a )?(?:(?:3\.?5\s*t(?:onne)?|lwb|mwb|swb|small|medium|large|luton|transit)\s+)?van|(?:a |one )?(?:luton|transit|lwb|mwb|swb)(?: van)? full|van full|vanload)\b/);return x?.[1]&&vagueVolume(x[1])?x[1]:null}
export function vehicleAssumption(m){let x=String(m||'').match(/\b(?:it|everything|all (?:of )?(?:it|this|that))?\s*(?:should|will|would|can|could)?\s*(?:all\s+)?(?:fit|go|be enough|do)\s+(?:in|into)?\s*(?:one|1|a)\s+(?:luton|transit|lwb|mwb|swb)(?: van)?\b|\b(?:one|1|a)\s+(?:luton|transit|lwb|mwb|swb)(?: van)?\s+(?:should|will|would)?\s*(?:do|be enough|fit)\b/i);return x?.[0]||null}
const vagueHelp=m=>/\b(plenty|loads?|lots?|enough) of help\b|\b(?:mates?|friends?|family|brother|sister|neighbou?r|people|someone|somebody) (?:will be|are|is) (?:there|around|present)\b/i.test(m)
const explicitNoHelp=m=>/\b(?:i|we) (?:can't|cannot|won't|will not|am not able to|are not able to) help(?: with)? (?:lift|lifting|load|loading|carry|carrying)\b|\b(?:no one|nobody|no-one) (?:can|will|is able to) help(?: with)? (?:lift|lifting|load|loading|carry|carrying)\b|\bdriver (?:will )?need(?:s)? to do all (?:the )?(?:lifting|loading|carrying)\b/i.test(m)
const partialHelp=m=>/\bhelp(?:ing)? (?:with )?(?:the )?(?:boxes?|bags?|light items?|small items?)\b[^.]{0,60}\b(?:but|not)\b[^.]{0,40}\b(?:sofa|wardrobe|bed|piano|safe|heavy|large|furniture)\b|\bcan help\b[^.]{0,50}\bbut (?:not|can't|cannot)\b/i.test(m)
const capableHelp=m=>/\b(?:i|we|they|he|she|my \w+|\d+ people) (?:can|will|are able to|is able to|are happy to|is happy to) help(?: with)? (?:lift|lifting|load|loading|unload|unloading|carry|carrying)\b|\b(?:can|will) help (?:the )?driver (?:lift|load|unload|carry)\b/i.test(m)
const fitIssue=m=>/\b(window[- ]?only|only (?:go|come|fit|move) (?:in|out|through) (?:via|through)? ?(?:an?|the)? ?(?:upstairs )?window|through (?:an?|the) (?:upstairs )?window|won't fit|wont fit|doesn't fit|does not fit|doorway.{0,30}(?:narrow|small|\d+\s*cm)|feet (?:had to|need to|must) come off|doors? (?:had to|need to|must) come off|hoist|balcony lift|crane.{0,20}(?:window|balcony)|only just came in)\b/i.test(m)
const fitPlan=m=>/\b(?:i|we|customer|seller) (?:can|will|'ll|will be able to) (?:remove|take off|take out|dismantle) (?:the )?(?:feet|doors?|window)\b|\b(?:feet|doors?|window) (?:can|will|are going to|is going to) (?:come off|be removed|come out)\b|\b(?:hoist|crane|lift) (?:is |has been )?(?:booked|arranged|available)\b/i.test(m)
export function deterministic(message,obj,j){let m=message.trim(),s=m.toLowerCase(),facts=[],replace=null,handled=false,ambiguity=null,contextNotes=[];let dur=durationEstimate(m);if(dur)contextNotes.push({kind:'customer_estimate',text:`Customer estimates job duration at approximately ${dur}`});let dist=distanceEstimate(m);if(dist)contextNotes.push({kind:'customer_estimate',text:`Customer estimates route/distance as ${dist}`});let rel=relativeReference(m);if(rel)contextNotes.push({kind:'relative_reference',text:`Customer described location/route relatively: ${rel}`});let vc=vanLoadClaim(m);if(vc)contextNotes.push({kind:'customer_estimate',text:`Customer described load only as '${vc}', which is not specific enough to size the job reliably`});let va=vehicleAssumption(m);if(va)contextNotes.push({kind:'customer_estimate',text:`Customer vehicle-capacity assumption: ${va}`});
let pureDate=obj==='ask_date'&&/^(?:tomorrow(?:\s+or\s+(?:the\s+)?day\s+(?:after|vafter))?|day after tomorrow)$/i.test(canon(m));if(/tomorrow\s+or\s+(?:the\s+)?day\s+(?:after|vafter)/i.test(s)){let a=add(today(),1),b=add(today(),2);facts.push(['date.iso_date',a],['date.alt',b],['date.flexibility',`${a} or ${b}`],['date.original_text','tomorrow or day after']);handled=pureDate}else if(/\bday after tomorrow\b/i.test(s)){facts.push(['date.iso_date',add(today(),2)],['date.original_text','day after tomorrow']);handled=pureDate}else if(/\btomorrow\b/i.test(s)){facts.push(['date.iso_date',add(today(),1)],['date.original_text','tomorrow']);handled=pureDate}let wd=s.match(/\bnext\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i);if(wd){facts.push(['date.iso_date',nextWeekday(wd[1])],['date.original_text',wd[0]]);if(obj==='ask_date'&&canon(m)===canon(wd[0]))handled=true}let tm=s.match(/\b(?:at|starting at|start at|around)\s+((?:1[0-2]|0?[1-9])(?::[0-5]\d)?\s*(?:am|pm))\b/i);if(tm)facts.push(['date.time_preference',tm[1].replace(/\s+/g,'')]);else if(obj==='ask_time'){let bt=s.match(/^\s*((?:1[0-2]|0?[1-9])(?::[0-5]\d)?\s*(?:am|pm))\s*$/i);if(bt){facts.push(['date.time_preference',bt[1].replace(/\s+/g,'')]);handled=true}}
if(obj==='ask_furniture'){let x=canon(m).match(/^(?:it's |it is |a )?(corner|l shaped|u shaped|chaise|recliner|modular|sectional|sofa bed)(?: sofa)?$/);if(x){replace=[/sofa bed/.test(x[1])?x[1]:`${x[1]} sofa`];handled=true}x=canon(m).match(/^(2|3|4) seater(?: sofa)?$/);if(x){replace=[`${x[1]}-seater sofa`];handled=true}x=canon(m).match(/^(single|double|triple|king|super king)(?: (wardrobe|bed))?$/);if(x){let g=generic(j)[0]||'',k=x[2]||(/wardrobe/i.test(g)?'wardrobe':/bed/i.test(g)?'bed':null);if(k){replace=[`${x[1]} ${k}`];handled=true}}}
if(obj==='ask_piano'){let x=canon(m).match(/^(upright|baby grand|grand|digital|electric)(?: piano)?$/);if(x){replace=[`${x[1]} piano`];handled=true}}
if(obj==='ask_animal'&&!unk(m)){let neg=/\b(no|without|not in)\b[^.]{0,20}\b(carrier|crate|cage)\b/i.test(m),contained=neg?'no':/\b(carrier|crate|cage|securely contained)\b/i.test(m)?'yes':null;facts.push(['animal.contained',contained],['animal.details',m]);handled=true}
if(['ask_collection_access','ask_delivery_access'].includes(obj)){let side=obj.includes('collection')?'collection':'delivery';if(/\bno (?:internal |inside )?stairs?\b/i.test(m))facts.push([`${side}.internal_stairs`,'no']);let ins=m.match(/\b(\d+|one|two|three|four|five|six)\s+(?:internal |inside )?stairs?\b/i);if(ins)facts.push([`${side}.internal_stairs`,ins[0]]);if(/\bno (?:outside|external) steps?\b/i.test(m))facts.push([`${side}.external_steps`,'no']);let ext=m.match(/\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\s+(?:outside|external) steps?\b/i);if(ext)facts.push([`${side}.external_steps`,ext[0]]);let carry=m.match(/\b(?:about |around |roughly )?(\d+\s*(?:m|metres?|meters?|yards?|ft|feet))\s*(?:carry|from (?:the )?(?:door|property) to (?:the )?van)\b/i);if(carry)facts.push([`${side}.carry_distance`,carry[0]]);let park=m.match(/\b(?:permit[- ]only parking|resident permit|double yellow|single yellow|loading bay|driveway|parking outside|park at the door|park by the door|parking close)\b/i);if(park)facts.push([`${side}.parking`,park[0]]);if(/\b(?:(?:van )?(?:can )?parks? (?:at|outside|by|next to) (?:the )?(?:door|property|entrance)|parking (?:at|outside|by|next to) (?:the )?(?:door|property|entrance)|driveway|no long carry)\b/i.test(m))facts.push([`${side}.carry_distance`,'van can park at/very near the property']);if(facts.some(x=>String(x[0]).startsWith(side+'.')))handled=true;else if(/^(?:no issues?|easy|straightforward|fine|all good|easy access)$/i.test(canon(m))){ambiguity='Please confirm the three access points separately: internal stairs/lift, outside steps, and how far the carry is from the van.';handled=true}}
let bothEnds=/\b(?:both ends|either end|at both (?:properties|addresses)|both (?:properties|addresses)|at collection and delivery|collection and delivery)\b/i.test(m);if(bothEnds){if(/\bno (?:internal |inside )?stairs?\b/i.test(m))facts.push(['collection.internal_stairs','no'],['delivery.internal_stairs','no']);if(/\bno (?:outside|external) steps?\b/i.test(m))facts.push(['collection.external_steps','no'],['delivery.external_steps','no']);if(/\b(?:van (?:can )?park(?:s|ing)?|parking)\s+(?:at|outside|by|next to)\s+(?:the )?(?:door|property|entrance)|\bdriveways?\b|\bno long carr(?:y|ies)\b/i.test(m))facts.push(['collection.carry_distance','van can park at/very near the property'],['delivery.carry_distance','van can park at/very near the property'])}
if(obj==='ask_vehicle_condition'){if(yes(m)){facts.push(['vehicle.runs','yes'],['vehicle.rolls','yes'],['vehicle.steers','yes'],['vehicle.brakes','yes'],['vehicle.fuel_leak','no'],['vehicle.oil_leak','no']);handled=true}else if(no(m)){ambiguity='Which part is a no — does it not run, roll, steer or brake normally, or is there a leak?';handled=true}}
if(obj==='ask_time'&&/^(flexible|any time|anytime|no preference|whenever)$/i.test(strip(m))){facts.push(['date.time_preference','flexible']);handled=true}if(obj==='confirm_unusual_time'&&yes(m)){facts.push(['unusual_time_confirmed',true]);handled=true}
if(obj==='ask_notable'&&(no(m)||(/\b(?:no|none|nothing|not any)\b/i.test(m)&&/\b(?:large|heavy|awkward|unusual)\b/i.test(m)))){facts.push(['notable','none']);handled=true}
if(obj==='ask_packing'&&(yes(m)||no(m))){facts.push(['packing',yes(m)?'all loose belongings boxed/bagged and ready':'not fully boxed/packed']);handled=true}
if(/\b(nothing|hardly anything|very little)\s+(?:is |will be )?(?:boxed|packed)\b|\bnothing boxed\b|\bhundreds? of (?:loose |individual )?(?:bits|items|pieces)\b/i.test(m)){facts.push(['packing','substantial loose/unboxed items']);let z=m.match(/\bhundreds? of (?:loose |individual )?(?:bits|items|pieces)\b/i);if(z)facts.push(['loose_items',z[0]])}let partialPack=m.match(/\b(?:mostly|partly|partially) (?:boxed|packed)\b|\b(?:packing|boxing) (?:it |them )?on the day\b/i);if(partialPack)facts.push(['packing',partialPack[0]]);if(obj==='ask_loose_items'&&!unk(m)){facts.push(['loose_items',m]);handled=true}
if(obj==='ask_volume'&&!unk(m)&&m.length<160){if(vc||vehicleAssumption(m)){handled=true}else{facts.push(['house_volume',m]);handled=true}}
if(obj==='ask_dismantling'){let c=canon(m);if(/already (?:dismantled|apart|taken apart)|already in pieces/.test(c)){facts.push(['dismantling_mode','already_dismantled']);handled=true}else if(/(?:i|we|customer).*(?:will|'ll) (?:dismantle|take .* apart)/.test(c)){facts.push(['dismantling_mode','customer']);handled=true}else if(/driver.*(?:dismantle|take .* apart)|need(?:s)? (?:the )?driver.*dismantle/.test(c)){facts.push(['dismantling_mode','driver']);handled=true}else if(no(m)){facts.push(['dismantling_mode','not_needed']);handled=true}}
if(obj==='ask_reassembly'&&(yes(m)||no(m))){facts.push(['reassembly_required',yes(m)?'yes':'no']);handled=true}
if(obj==='ask_appliance_plumbing'){let c=canon(m);if(no(m)||/\b(no washing machine|no dishwasher|none|neither)\b/.test(c)){facts.push(['appliances.present','no']);handled=true}else{if(/\b(washing machine|dishwasher|appliance)\b/.test(c)||yes(m))facts.push(['appliances.present','yes']);if(/\b(already disconnected|will be disconnected|customer.*disconnect|i.*disconnect|we.*disconnect)\b/.test(c))facts.push(['appliances.disconnected','yes']);else if(/\b(driver.*disconnect|needs? disconnect|need.*disconnect|not disconnected|still connected)\b/.test(c))facts.push(['appliances.disconnected','no']);if(/\b(reconnect|replumb|plumb.*back|connect.*back)\b/.test(c))facts.push(['appliances.reconnect_requested','yes']);else if(/\b(no reconnect|do not reconnect|don't reconnect|wont need reconnect|won't need reconnect)\b/.test(c))facts.push(['appliances.reconnect_requested','no']);if(facts.some(x=>String(x[0]).startsWith('appliances.')))handled=true}}
if(obj==='ask_safe'&&!unk(m)){facts.push(['safe',m]);handled=true}
if(obj==='ask_passenger_details'&&(no(m)||/^(nothing|no luggage|no special requirements|no luggage no special requirements)$/i.test(canon(m)))){facts.push(['passenger.luggage','none'],['passenger.special','none']);handled=true}
if(obj==='ask_waste_hazard'&&(no(m)||/^(nothing hazardous|no hazardous items)$/i.test(canon(m)))){facts.push(['waste.hazard','none']);handled=true}
if(explicitNoHelp(m)){facts.push(['customer_assistance','no'],['assistance_detail','none - customer says no capable lifting help']);if(obj==='ask_assistance')handled=true}else if(partialHelp(m)){facts.push(['customer_assistance','yes'],['assistance_detail',`partial - ${m}`]);if(obj==='ask_assistance')handled=true}else if(capableHelp(m)){facts.push(['customer_assistance','yes'],['assistance_detail',`capable lifting help stated - ${m}`]);if(obj==='ask_assistance')handled=true}else if(obj==='ask_assistance'&&vagueHelp(m)){ambiguity='Are the people there actually able and willing to help lift/load the larger items, or will the driver need to allow for all heavy lifting?';handled=true}
if(fitIssue(m)){facts.push(['fit_access_issue',m]);if(fitPlan(m))facts.push(['fit_access_plan',m])}if(obj==='ask_fit_access'&&!unk(m)){facts.push(['fit_access_plan',m]);handled=true}
if(/\b(washing machine|dishwasher)\b/i.test(m))facts.push(['appliances.present','yes']);if(/\b(?:washing machine|dishwasher)\b[^.]{0,60}\b(?:already disconnected|disconnected before|will be disconnected)\b|\b(?:already disconnected|will be disconnected)\b[^.]{0,60}\b(?:washing machine|dishwasher)\b/i.test(m))facts.push(['appliances.disconnected','yes']);if(/\b(?:driver|mover).{0,40}\b(?:disconnect|unplumb)\b/i.test(m))facts.push(['appliances.disconnected','no']);if(/\b(?:reconnect|replumb|plumb.*back|connect.*back)\b/i.test(m))facts.push(['appliances.reconnect_requested','yes'])
let lug=m.match(/\b((?:\d+|one|two|three|four|five|six)\s+(?:suitcases?|bags?|cases?))\b/i);if(lug)facts.push(['passenger.luggage',lug[1]]);let qty=m.match(/\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|twenty)\s+(?=(?:boxed|crated|wrapped|pallets?|chairs?|tables?|units?|boxes?|items?|parcels?|packages?|cases?|desks?|appliances?|bikes?|computers?|monitors?|screens?|cartons?|crates?)\b)/i);if(qty)facts.push(['specialist.quantity',qty[1]]);if(/\bsafe\b/i.test(m)&&(/\b(?:small|medium|large|tiny|compact|heavy)\b/i.test(m)||/\b\d+(?:\.\d+)?\s*(?:kg|kilograms?|lb|lbs|cm|mm|m)\b/i.test(m)))facts.push(['safe',m]);if(/\b(completion(?: day)?|property chain|waiting for keys|key release|must be out|need to be out|out by)\b/i.test(m))facts.push(['completion',m]);if(/\b(must arrive by|arrive by|must be there by|delivery by|latest(?: acceptable)?(?: delivery| arrival)?(?: time)?(?: is)?|load[- ]?in by)\b/i.test(m))facts.push(['specialist.deadline',m]);return{facts,replace,handled,ambiguity,unknown:unk(m),contextNotes}}
