// @ts-nocheck
import { createClient } from "npm:@supabase/supabase-js@2.95.0"

const TARGET="vanhub-chat-kernel", ORIGIN="https://www.vanhubuk.com", WAIT=725, DEFAULT_CONCURRENCY=4
function admin(){const u=Deno.env.get("SUPABASE_URL")||"";let k=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";if(!k)try{k=JSON.parse(Deno.env.get("SUPABASE_SECRET_KEYS")||"{}").default||""}catch{};if(!u||!k)throw Error("ENV");return createClient(u,k,{auth:{persistSession:false}})}
const sleep=ms=>new Promise(r=>setTimeout(r,ms)), norm=v=>String(v||"").toLowerCase().replace(/\s+/g," ").trim()
function decodeSet(v){const b=Uint8Array.from(atob(v),c=>c.charCodeAt(0)),x=JSON.parse(new TextDecoder().decode(b));if(!Array.isArray(x))throw Error("SCENARIO_SET_NOT_ARRAY");return x}
async function callKernel(sessionId,message,pageContext){const url=`${Deno.env.get("SUPABASE_URL")}/functions/v1/${TARGET}`,body={action:"message",sessionId:sessionId||undefined,message,pageContext};let last;for(let n=0;n<2;n++){const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","Origin":ORIGIN},body:JSON.stringify(body)});let p={};try{p=await r.json()}catch{};last={status:r.status,p};if(r.status!==429)return last;await sleep(WAIT+100)}return last}
async function state(sb,id){if(!id)return null;const r=await sb.from("job_drafts").select("job_data,field_status,last_objective,ready_for_review,state_revision,status,review_summary,job_id").eq("session_id",id).maybeSingle();if(r.error)throw r.error;if(!r.data)return null;return {...r.data,ready_for_review:!!r.data.ready_for_review,state_revision:Number(r.data.state_revision||0)}}
function flags(t,st){const f=[];for(let i=0;i<t.length;i++){const x=t[i];if(i&&norm(x.reply)&&norm(x.reply)===norm(t[i-1].reply))f.push("identical_reply_repeat");if(x.ready_for_review&&i<t.length-1)f.push("ready_before_script_end");if(x.http_status!==200)f.push(`http_${x.http_status}`)}if(st?.job_id)f.push("unexpected_job_created");return [...new Set(f)]}
async function scenario(sb,runId,batch,s){const turns=Array.isArray(s?.turns)?s.turns.filter(x=>typeof x==="string"&&x.trim()):[],transcript=[];let sessionId=null,error=null;const pc={title:"vanhub-chat-kernel acceptance",url:`internal://qa/kernel-v80/batch-${batch}/${String(s?.id||"unknown")}`,isDriverProfile:false};try{for(let i=0;i<turns.length;i++){if(i)await sleep(WAIT);const r=await callKernel(sessionId,turns[i],pc),p=r?.p||{};if(!sessionId&&typeof p.sessionId==="string")sessionId=p.sessionId;transcript.push({turn:i+1,user:turns[i],reply:p.reply||null,objective:p.objective||null,stage:p.stage||null,progress:p.progress??null,ready_for_review:!!p.readyForReview,http_status:r?.status??null});if(r?.status!==200){error=`HTTP_${r?.status}:${p?.error||"unknown"}`;break}}}catch(e){error=e instanceof Error?e.message:String(e)}let st=null;try{st=await state(sb,sessionId)}catch(e){error||=`STATE:${e instanceof Error?e.message:String(e)}`};const fl=flags(transcript,st);const ins=await sb.from("qa_chatbot_acceptance_results").insert({run_id:runId,scenario_id:String(s?.id||"unknown"),scenario_name:String(s?.name||s?.id||"unnamed"),scenario_group:String(s?.group||"ungrouped"),input_turns:turns,transcript,final_state:st,auto_flags:fl,error});if(ins.error)throw ins.error;return{error,flags:fl}}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let next=0;async function w(){for(;;){const i=next++;if(i>=items.length)return;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},w));return out}
Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok");if(req.method!=="POST")return Response.json({error:"Method not allowed"},{status:405});let b={};try{b=await req.json()}catch{return Response.json({error:"Invalid JSON"},{status:400})};const batch=Number(b.batch),offset=Math.max(0,Number(b.offset||0)),limit=b.limit==null?null:Math.max(1,Math.min(100,Number(b.limit)));if(![1,2,3,4].includes(batch))return Response.json({error:"batch must be 1..4"},{status:400});const sb=admin(),set=await sb.from("qa_chatbot_acceptance_scenario_sets").select("payload_b64").eq("batch",batch).maybeSingle();if(set.error||!set.data)return Response.json({error:"Scenario set not found"},{status:404});let list;try{list=decodeSet(set.data.payload_b64).slice(offset,limit==null?undefined:offset+limit)}catch(e){return Response.json({error:String(e)},{status:500})};const rr=await sb.from("qa_chatbot_acceptance_runs").insert({batch,status:"running",started_at:new Date().toISOString(),summary:{target:TARGET,source:"github-canonical",offset,limit,scenarios:list.length}}).select("id").single();if(rr.error)return Response.json({error:rr.error.message},{status:500});const id=rr.data.id;try{const rs=await mapLimit(list,Math.max(1,Math.min(8,Number(b.concurrency||DEFAULT_CONCURRENCY))),x=>scenario(sb,id,batch,x));let errors=0,flagged=0;const fc={};for(const r of rs){if(r?.error)errors++;if(r?.flags?.length)flagged++;for(const f of r?.flags||[])fc[f]=(fc[f]||0)+1}const summary={target:TARGET,source:"github-canonical",scenarios:rs.length,errors,flagged,flag_counts:fc,offset,limit};await sb.from("qa_chatbot_acceptance_runs").update({status:"completed",finished_at:new Date().toISOString(),summary,error:null}).eq("id",id);return Response.json({run_id:id,batch,...summary})}catch(e){const msg=e instanceof Error?e.message:String(e);await sb.from("qa_chatbot_acceptance_runs").update({status:"failed",finished_at:new Date().toISOString(),error:msg}).eq("id",id);return Response.json({run_id:id,error:msg},{status:500})}})
