// @ts-nocheck
import {createClient} from "npm:@supabase/supabase-js@2.95.0"

const API='https://api.openai.com/v1'
const VS=()=>Deno.env.get('VANHUB_VECTOR_STORE_ID')||'vs_6a84539e4a348191956211ede0cf1a26'
const MODEL=()=>Deno.env.get('OPENAI_REFINERY_MODEL')||'gpt-4.1-mini'
const MAX_CHARS=18000

function admin(){const u=Deno.env.get('SUPABASE_URL')||'';let k=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'';if(!k)try{k=JSON.parse(Deno.env.get('SUPABASE_SECRET_KEYS')||'{}').default||''}catch{};if(!u||!k)throw Error('ENV');return createClient(u,k,{auth:{persistSession:false}})}
function key(){const k=Deno.env.get('OPENAI_API_KEY')||'';if(!k)throw Error('NO_OPENAI_API_KEY');return k}
async function oa(path,init={}){const r=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${key()}`,'Content-Type':'application/json','OpenAI-Beta':'assistants=v2',...(init.headers||{})}});let p={};try{p=await r.json()}catch{};if(!r.ok)throw Error(`OPENAI_${r.status}:${p?.error?.message||JSON.stringify(p)}`);return p}
function blocksOf(p){if(Array.isArray(p?.content))return p.content;if(Array.isArray(p?.data))return p.data;if(Array.isArray(p))return p;return []}
async function sourceText(fileId){const p=await oa(`/vector_stores/${VS()}/files/${encodeURIComponent(fileId)}/content`);return blocksOf(p).map(x=>String(x?.text||x?.content||'')).join('\n\n')}
function splitText(text,max=MAX_CHARS){const paras=String(text||'').split(/\n{2,}/),parts=[];let buf='',cursor=0,start=0;const push=()=>{if(!buf)return;parts.push({text:buf,start,end:start+buf.length});cursor=start+buf.length;buf=''};for(const raw of paras){const p=raw.trim();if(!p)continue;if(p.length>max){push();for(let i=0;i<p.length;i+=max){const t=p.slice(i,i+max);parts.push({text:t,start:cursor,end:cursor+t.length});cursor+=t.length}start=cursor;continue}const add=(buf?'\n\n':'')+p;if(buf&&buf.length+add.length>max){push();start=cursor;buf=p}else{if(!buf)start=cursor;buf+=add}}push();return parts}
const SYS=`You are distilling private real-world UK removals/transport training material into a PUBLIC, sanitised engineering knowledge corpus for VanHub. Extract every distinct operational lesson in this source segment that could improve chatbot qualification, questioning, safety, quote accuracy, state validation, or regression testing. Do not omit edge cases merely because they look repetitive: merge only truly duplicate lessons. Do not reproduce names, phone numbers, email addresses, URLs, exact customer addresses, identifiable transcript wording, or other personal data. Customer-language patterns must be paraphrased/generic. Synthetic test turns must be newly written and must not copy identifiable source wording. Town names may be generic/common but never include a precise customer address. Retrieved/refinery knowledge is policy and questioning context only; it is NEVER customer evidence and must never populate a customer operational field without literal current-message evidence. Distinguish what the bot should ask from what it may safely infer. Preserve trade-practice nuance, especially vague loads, access, stairs/steps, carries, parking, dismantling responsibility, loose/unboxed contents, capable vs vague helpers, appliance plumbing exclusions, completion/key waits, vehicle condition/loading, specialist loads, shop/marketplace collections, time windows, safety/manual-review triggers, and customer understatement. If a source example itself makes an unsafe inference, record the anti-assumption instead of perpetuating it.`
const DOMAINS=['route','inventory','access','parking','carry','stairs','dismantling','assistance','packing','appliance','house_move','flat_move','courier','business_delivery','vehicle','motorbike','specialist','waste','animal','passenger','date_time','completion','contact','safety','quote','handoff','faq','normalisation','customer_language','other']
const KINDS=['rule','questioning_pattern','anti_assumption','risk_signal','normalisation','safety','handoff','edge_case','customer_language']
const SCHEMA={type:'object',additionalProperties:false,required:['part_summary','coverage_notes','pii_removed','units'],properties:{part_summary:{type:'string'},coverage_notes:{type:'string'},pii_removed:{type:'boolean'},units:{type:'array',items:{type:'object',additionalProperties:false,required:['domain','kind','importance','rule','bot_should','bot_must_not','customer_pattern','synthetic_test_turns','expected_test_behavior','source_anchor','requires_deterministic_guard','runtime_retrieval_only'],properties:{domain:{type:'string',enum:DOMAINS},kind:{type:'string',enum:KINDS},importance:{type:'string',enum:['critical','high','medium']},rule:{type:'string'},bot_should:{type:'string'},bot_must_not:{type:['string','null']},customer_pattern:{type:['string','null']},synthetic_test_turns:{type:'array',items:{type:'string'}},expected_test_behavior:{type:'string'},source_anchor:{type:['string','null']},requires_deterministic_guard:{type:'boolean'},runtime_retrieval_only:{type:'boolean'}}}}}}
function outputText(p){if(typeof p?.output_text==='string')return p.output_text;for(const i of p?.output||[])for(const c of i?.content||[])if(c?.type==='output_text'&&typeof c.text==='string')return c.text;return null}
let redactions=0
function cleanString(v){let s=String(v??'');const pats=[/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi,/\b(?:\+44\s?7\d{3}|07\d{3})[\s-]?\d{3}[\s-]?\d{3}\b/g,/https?:\/\/\S+/gi,/\b[A-Z]{1,2}\d[A-Z\d]?\s*\d[A-Z]{2}\b/gi,/\b\d{1,4}\s+[A-Za-z][A-Za-z .'-]{1,40}\s+(?:Road|Rd|Street|St|Lane|Ln|Drive|Dr|Avenue|Ave|Close|Court|Way|Crescent|Place|Terrace)\b/gi];for(const re of pats)s=s.replace(re,()=>{redactions++;return '[redacted]' });return s}
function sanitize(v){if(typeof v==='string')return cleanString(v);if(Array.isArray(v))return v.map(sanitize);if(v&&typeof v==='object'){const o={};for(const [k,x] of Object.entries(v))o[k]=sanitize(x);return o}return v}
async function distill(meta,part,partIndex,partTotal){const body={model:MODEL(),store:false,max_output_tokens:12000,input:[{role:'system',content:SYS},{role:'user',content:JSON.stringify({source_file:meta.filename,source_type:meta.source_type,part_index:partIndex,part_total:partTotal,source_segment:part.text})}],text:{format:{type:'json_schema',name:'vanhub_refinery_public_distill',strict:true,schema:SCHEMA}}};const p=await oa('/responses',{method:'POST',body:JSON.stringify(body)}),t=outputText(p);if(!t)throw Error('OPENAI_EMPTY');redactions=0;const distilled=sanitize(JSON.parse(t));distilled.pii_removed=true;distilled.sanitizer_redactions=redactions;return {distilled,model:p.model||MODEL(),usage:p.usage||null}}
async function planFile(sb,fileId){const r=await sb.schema('private').from('qa_refinery_distill').select('*').eq('file_id',fileId).maybeSingle();if(r.error||!r.data)throw r.error||Error('UNKNOWN_FILE');const text=await sourceText(fileId),parts=splitText(text);const rows=parts.map((p,i)=>({file_id:fileId,part_index:i,part_total:parts.length,char_start:p.start,char_end:p.end,status:'queued',updated_at:new Date().toISOString()}));const u=await sb.schema('private').from('qa_refinery_distill_parts').upsert(rows,{onConflict:'file_id,part_index'});if(u.error)throw u.error;const p=await sb.schema('private').from('qa_refinery_distill').update({content_blocks:parts.length,content_chars:text.length,status:'queued',error:null,updated_at:new Date().toISOString()}).eq('file_id',fileId);if(p.error)throw p.error;return {file_id:fileId,filename:r.data.filename,content_chars:text.length,parts:parts.length}}
async function processPart(sb,fileId,partIndex){const mr=await sb.schema('private').from('qa_refinery_distill').select('*').eq('file_id',fileId).maybeSingle();if(mr.error||!mr.data)throw mr.error||Error('UNKNOWN_FILE');const text=await sourceText(fileId),parts=splitText(text),part=parts[partIndex];if(!part)throw Error('PART_OUT_OF_RANGE');await sb.schema('private').from('qa_refinery_distill_parts').upsert({file_id:fileId,part_index:partIndex,part_total:parts.length,char_start:part.start,char_end:part.end,status:'distilling',error:null,updated_at:new Date().toISOString()},{onConflict:'file_id,part_index'});try{const x=await distill(mr.data,part,partIndex,parts.length);const u=await sb.schema('private').from('qa_refinery_distill_parts').update({status:'distilled',distilled:x.distilled,model:x.model,usage:x.usage,error:null,updated_at:new Date().toISOString()}).eq('file_id',fileId).eq('part_index',partIndex);if(u.error)throw u.error;const cr=await sb.schema('private').from('qa_refinery_distill_parts').select('status').eq('file_id',fileId);if(cr.error)throw cr.error;const done=(cr.data||[]).filter(x=>x.status==='distilled').length,failed=(cr.data||[]).filter(x=>x.status==='failed').length;await sb.schema('private').from('qa_refinery_distill').update({status:done===parts.length?'distilled':failed?'failed':'distilling',updated_at:new Date().toISOString()}).eq('file_id',fileId);return {file_id:fileId,filename:mr.data.filename,part_index:partIndex,part_total:parts.length,units:x.distilled.units?.length||0,redactions:x.distilled.sanitizer_redactions||0,status:'distilled'}}catch(e){const msg=e instanceof Error?e.message:String(e);await sb.schema('private').from('qa_refinery_distill_parts').update({status:'failed',error:msg,updated_at:new Date().toISOString()}).eq('file_id',fileId).eq('part_index',partIndex);await sb.schema('private').from('qa_refinery_distill').update({status:'failed',error:msg,updated_at:new Date().toISOString()}).eq('file_id',fileId);throw e}}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok');if(req.method!=='POST')return Response.json({error:'Method not allowed'},{status:405});let b={};try{b=await req.json()}catch{return Response.json({error:'Invalid JSON'},{status:400})};const sb=admin();try{if(b.action==='plan_file'){if(!b.file_id)return Response.json({error:'file_id required'},{status:400});return Response.json(await planFile(sb,String(b.file_id)))}if(b.action==='process_part'){if(!b.file_id||b.part_index==null)return Response.json({error:'file_id and part_index required'},{status:400});return Response.json(await processPart(sb,String(b.file_id),Number(b.part_index)))}return Response.json({error:'action must be plan_file or process_part'},{status:400})}catch(e){return Response.json({error:e instanceof Error?e.message:String(e)},{status:500})}})
