// @ts-nocheck
const DEFAULT_STORE='vs_6a84539e4a348191956211ede0cf1a26'
const API='https://api.openai.com/v1'

function key(){const k=Deno.env.get('OPENAI_API_KEY')||'';if(!k)throw Error('NO_OPENAI_API_KEY');return k}
function storeId(){return Deno.env.get('VANHUB_VECTOR_STORE_ID')||DEFAULT_STORE}
async function oa(path,init={}){const r=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${key()}`,'Content-Type':'application/json',...(init.headers||{})}});let p;const ct=r.headers.get('content-type')||'';if(ct.includes('application/json')){try{p=await r.json()}catch{p={}}}else p=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}:${typeof p==='string'?p:JSON.stringify(p)}`);return p}
async function rawFile(fileId){const r=await fetch(`${API}/files/${encodeURIComponent(fileId)}/content`,{headers:{Authorization:`Bearer ${key()}`}});const t=await r.text();if(!r.ok)throw Error(`OPENAI_${r.status}:${t}`);return t}
async function listVectorFiles(vs){let out=[],after=null;for(let page=0;page<100;page++){let q=`?limit=100&order=asc${after?`&after=${encodeURIComponent(after)}`:''}`;const p=await oa(`/vector_stores/${vs}/files${q}`);out.push(...(p.data||[]));if(!p.has_more||!p.last_id)break;after=p.last_id}return out}
async function mapLimit(items,limit,fn){const out=new Array(items.length);let n=0;async function w(){for(;;){const i=n++;if(i>=items.length)return;out[i]=await fn(items[i],i)}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},w));return out}
async function inventory(vs){const [store,files]=await Promise.all([oa(`/vector_stores/${vs}`),listVectorFiles(vs)]);const enriched=await mapLimit(files,4,async f=>{let meta=null;try{meta=await oa(`/files/${f.id}`)}catch(e){meta={error:String(e)}}return {id:f.id,status:f.status,usage_bytes:f.usage_bytes??null,created_at:f.created_at??null,attributes:f.attributes??null,chunking_strategy:f.chunking_strategy??null,last_error:f.last_error??null,filename:meta?.filename??null,bytes:meta?.bytes??null,purpose:meta?.purpose??null,file_created_at:meta?.created_at??null,metadata_error:meta?.error??null}});return {vector_store:{id:store.id,name:store.name??null,status:store.status??null,usage_bytes:store.usage_bytes??null,file_counts:store.file_counts??null,created_at:store.created_at??null,expires_at:store.expires_at??null,last_active_at:store.last_active_at??null,metadata:store.metadata??null},files:enriched,total_files:enriched.length,total_source_bytes:enriched.reduce((a,x)=>a+(Number(x.bytes)||0),0),total_vector_usage_bytes:enriched.reduce((a,x)=>a+(Number(x.usage_bytes)||0),0)}}
async function contentIndex(fileId){const t=await rawFile(fileId);return {file_id:fileId,total_chars:t.length,preview:t.slice(0,1600)}}
async function contentPage(fileId,start=0,limit=20000){const t=await rawFile(fileId),s=Math.max(0,Number(start)||0),l=Math.max(1000,Math.min(30000,Number(limit)||20000));return {file_id:fileId,total_chars:t.length,start:s,limit:l,has_more:s+l<t.length,text:t.slice(s,s+l)}}
async function searchStore(vs,query,max=50){return oa(`/vector_stores/${vs}/search`,{method:'POST',body:JSON.stringify({query:String(query||''),max_num_results:Math.max(1,Math.min(50,Number(max)||50))})})}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok');if(req.method!=='POST')return Response.json({error:'Method not allowed'},{status:405});let b={};try{b=await req.json()}catch{return Response.json({error:'Invalid JSON'},{status:400})};const vs=String(b.vector_store_id||storeId());try{if(b.action==='inventory')return Response.json(await inventory(vs));if(b.action==='content_index'){if(!b.file_id)return Response.json({error:'file_id required'},{status:400});return Response.json(await contentIndex(String(b.file_id)))}if(b.action==='content'){if(!b.file_id)return Response.json({error:'file_id required'},{status:400});return Response.json(await contentPage(String(b.file_id),b.start,b.limit))}if(b.action==='search'){if(!String(b.query||'').trim())return Response.json({error:'query required'},{status:400});return Response.json(await searchStore(vs,b.query,b.max_num_results))}return Response.json({error:'action must be inventory, content_index, content, or search'},{status:400})}catch(e){return Response.json({error:e instanceof Error?e.message:String(e)},{status:500})}})
